### ISSUE TITLE
Locator error for an oversize book

### ISSUE THREAD

**Issue by tampakis** [pulibrary/firestone_locator#14]
Not sure where the underlying error is but the locator errors for this entry: https://catalog.princeton.edu/catalog/856959
Oversize SH383.5.S26 R53 1992q
https://library.princeton.edu/locator/index.php?loc=f&id=856959

**Comment by carolyncole** [comment]
https://catalog.princeton.edu/catalog/998569593506421 currently has no error when you click the locator button
