### ISSUE TITLE
Items at the circulation desk

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/firestone_locator#26]
The old site used to say ask for help on this item:
https://library.princeton.edu/locator/index.php?loc=resc&id=943304&embed=true
![Screen Shot 2019-10-15 at 2 47 32 PM](https://user-images.githubusercontent.com/1599081/66860267-dfa8fd80-ef5a-11e9-90f4-7074702278db.png)

The new site is now showing a map:
https://libwebprod/locator/index.php?loc=resc&id=943304&embed=true
![Screen Shot 2019-10-15 at 2 47 48 PM](https://user-images.githubusercontent.com/1599081/66860295-ed5e8300-ef5a-11e9-9e7a-d47f76c76a9c.png)

According to the new snap ticket they want to show a map to circulation: https://princeton.service-now.com/nav_to.do?uri=incident.do?sys_id=7f3be905dba404d4a341de82ca96190f

**Comment by carolyncole** [comment]
Here is another one that is not working: https://catalog.princeton.edu/catalog?utf8=✓&search_field=all_fields&q=Evicted+%3A+poverty+and+profit+in+the+American+city

https://catalog.princeton.edu/catalog/10926564

**Comment by kevinreiss** [comment]
This may be data problem. This view doesn't work, https://bibdata.princeton.edu/bibliographic/10926564/items.

**Comment by carolyncole** [comment]
That could be part of the problem, but this one does have items: https://bibdata.princeton.edu/bibliographic/9573790/items

I'll take a look at it tomorrow.

**Comment by carolyncole** [comment]
Here are two more issues: https://library.princeton.edu/locator/index.php?loc=resc&id=4830941&embed=true & https://locator-prod.princeton.edu/index.php?loc=resc&id=6095425&embed=true

**Comment by kevinreiss** [comment]
This is looking good from my perspective. Okay to close?

**Comment by carolyncole** [comment]
@kevinreiss I have one more PR, give the two additional issues I logged.  
I added some tests and rewrote some of the code.
