### ISSUE TITLE
Multiple Copies in Multiple Locations

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/firestone_locator#32]
This items has multiple locations for the two copies.  At this point orangelight sends the locator the same link for both copies, and we return the same information for both:

The behavior is exactly the same as the old version of the code

https://catalog.princeton.edu/catalog/1273320

https://libwebprod/locator/index.php?loc=f&id=1273320&embed=true

https://locator-prod.princeton.edu/index.php?loc=f&id=1273320&embed=true #missing copy from orangelight
https://locator-prod.princeton.edu/index.php?loc=f&id=1273320&embed=true # available copy from orangelight

To make matters worse the one copy has a Richardson call number, so it would not sort with our mapping even if we somehow knew to get the second copy.

I believe to fix this we may need to change both orangelight and the locator.

**Comment by carolyncole** [comment]
These are missing, but instead of sending the person to the circulation desk it shows it's old location
- https://locator-prod.princeton.edu/index.php?loc=f&id=994986&embed=true
- https://locator-prod.princeton.edu/index.php?loc=f&id=1707253&embed=true
- https://locator-prod.princeton.edu/index.php?loc=f&id=1287942&embed=true


These are missing and go to the circulation desk
- https://locator-prod.princeton.edu/index.php?loc=f&id=2004363&embed=true
- https://locator-prod.princeton.edu/index.php?loc=f&id=2930025&embed=true
- https://locator-prod.princeton.edu/index.php?loc=f&id=3344112&embed=true

Here is an example of two different call numbers
- https://locator-prod.princeton.edu/index.php?loc=f&id=1382929&embed=true
   https://locator-prod.princeton.edu/index.php?loc=f&id=1382929&embed=true

**Comment by sdellis** [comment]
Fall back to original location if item is missing.
